---
abstract: 'Riap::TCP client'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Access-TCP-Client
requires:
  Perinci::Access::Base: 0.19
  Riap: 1.1.15
  Tie::Cache: 0
  URI: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Perinci-Access-TCP-Client
  repository: http://github.com/sharyanto/perl-Perinci-Access-TCP-Client
version: 0.03
